name: wechat

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: wechat-work robot message
        uses: fifsky/wechat-work-action@master
        with:
          url: ${{ secrets.WECHATWORK_WEBHOOK}}
          type: markdown
          content: |
            # Tips
            ## Hello
            > from github action message
            > ^_^
            - github: ${{ toJson(github) }}
            - job status: ${{ job.status }}